version: '2'

services:
    elasticsearch:
        build: ./elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - ./elasticsearch/config:/usr/share/elasticsearch/config
        networks:
          - docker_elk

    kibana:
        build: ./kibana
        ports:
            - "5601:5601"
        volumes:
            - ./kibana/config/:/etc/kibana
        links:
            - elasticsearch
        networks:
          - docker_elk

    logstash:
        build: ./logstash
        command: -f /etc/logstash/conf.d/logstash.conf
        volumes:
          #- ./logstash/conf:/usr/share/logstash/config
          - ./logstash/conf:/etc/logstash/conf.d
        ports:
            - "5044:5044"
            # - "9600:9600"
        links:
            - elasticsearch
        networks:
          - docker_elk

    filebeat:
        build: ./filebeat
        volumes:
            - ./filebeat/logs:/tmp/logs
        links:
            - logstash
            - elasticsearch
        networks:
          - docker_elk

networks:
  docker_elk:
    driver: bridge