FROM docker.elastic.co/elasticsearch/elasticsearch:5.2.1

# RUN bin/elasticsearch-plugin install mobz/elasticsearch-head


# FROM elasticsearch:latest
# RUN bin/elasticsearch-plugin install x-pack

# COPY ./config/elasticsearch.yml config/elasticsearch.yml

# EXPOSE 9200:9200 9300:9300